@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.component.panel.titled"
    
    KivaKitPanel <|-- TitledPanel
    class TitledPanel
    {
        --(constructors)--
        +TitledPanel()
        --
        +void content(JComponent child)
        +void icon(ImageIcon)
        +void title(String title)
    }
    
@enduml

