@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.component.fader"
    
    JLabel <|-- Fader
    class Fader
    {
        --(constructors)--
        +Fader(Color, int, int, Duration)
        --
        +void fadeIn()
        +void fadeOut()
    }
    
@enduml

