@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.graphics.image"
    
    class ImageResource
    {
        --(constructors)--
        +ImageResource(PackageResource)
        --
        +Image image(int width, int height)
        +Image image()
        +ImageResource of(PackageResource)
        +ImageResource of(Class<?> type, String path)
    }
    
    class Images
    {
        --
        +BufferedImage buffer(Image)
    }
    
@enduml

