@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.component.panel.output"
    
    KivaKitPanel <|-- OutputPanel
    class OutputPanel
    {
        --(constructors)--
        +OutputPanel(Type)
        --
        +void font(Font)
        +void html(String html, Object... arguments)
        +void text(String text, Object... arguments)
    }
    
    enum OutputPanel.Type
    {
        FIXED_WIDTH
        VARIABLE_WIDTH
    }
    
@enduml

