@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.component.panel.section"
    
    KivaKitPanel <|-- Section
    class Section
    {
        --(constructors)--
        +Section()
        --
        +void content(JComponent child)
        +void icon(ImageIcon)
        +void title(String title)
    }
    
@enduml

