@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.component.layout.separator"
    
    KivaKitPanel <|-- HorizontalSeparator
    class HorizontalSeparator
    {
        --(constructors)--
        +HorizontalSeparator()
        +HorizontalSeparator(Color)
    }
    
@enduml

