@startuml

    !include ../lexakai/lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.graphics"
    
    class Geometry
    {
        --(primitive)--
        +Point2D.Double to2d(Point)
        +Point2D.Double to2d(Point2D)
    }
    
@enduml

