
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#
#  © 2021 Telenav, Inc.
#  Licensed under Apache License, Version 2.0
#
#///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#
# GitHub action that builds this project when code is checked in to the master, develop,
# feature or release branches. When the build succeeds on GitHub it is safe to merge or
# publish the branch.
#

name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - 'features/**'
      - 'releases/**'
  pull_request:
    branches:
      - master
      - develop
      - 'features/**'
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build
        run: mvn --no-transfer-progress --batch-mode clean install
