
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master develop features/** releases/** ]
  pull_request:
    branches: [ master develop features/** releases/** ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Build
        run: mvn --no-transfer-progress --batch-mode clean install
